# define our source to loook for gems
source "http://rubygems.org/"

# declare the sinatra dependency
gem "sinatra"
gem 'sinatra-reloader', '~> 1.0'
gem 'rmagick', '~> 2.13.3', require: 'RMagick'
gem 'httparty'
gem 'screencap'
gem 'newrelic_rpm'
gem 'redis'


# setup our test group and require rspec
group :test do
  gem "rspec"
end

# require a relative gem version
gem "i18n", "~> 0.4.1"

